# Generated by Django 5.2.6 on 2025-09-13 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=100)),
                ('foto_gato', models.URLField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatos', to='Catapp.dono')),
            ],
        ),
    ]
