# Generated by Django 5.2.6 on 2025-09-13 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gato',
            name='api_id',
            field=models.CharField(default='sem_api', max_length=100, unique=True, verbose_name='ID da API'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gato',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='Catapp.dono', verbose_name='dono'),
        ),
    ]
