# Generated by Django 5.2.6 on 2025-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catapp', '0002_gato_api_id_alter_gato_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
