# Generated by Django 5.2.6 on 2025-09-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catapp', '0004_dono_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dono',
            name='endereco',
        ),
        migrations.AddField(
            model_name='dono',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
